---
- block:
   - name: Copy netdata rpm to remote
     copy: src=./{{ netdata }} dest=/home/{{user_name}}/{{ netdata }}

   - name: Install netdata
     dnf: name=/home/{{user_name}}/{{ netdata }} state=present

   - name: Put netdata.conf
     template: src=netdata.conf dest=/etc/netdata/netdata.conf

   - name: Put statsd apps config to netdata
     template: src=statsd_app.conf.j2 dest=/etc/netdata/statsd.d/edge_{{ item }}.conf
     with_items: "{{ resources }}"

   - name: Put apps_groups.conf
     template: src=apps_groups.conf dest=/etc/netdata/apps_groups.conf

   - name: Start netdata
     service: name=netdata state=started

   - name: Restart netdata
     service: name=netdata state=restarted enabled=yes
  become: yes
  tags: ['netdata']
